id: IDE9B3BD9
ocr_import_info:
  timestamp: '2023-09-27T08:52:31.706222+00:00'
  batch_id: batch-8d06
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 09:19:31.128904+00:00
last_modified: 2023-09-27 09:19:31.128912+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5476
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5476
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཛོད་ཀྱི་རྣམ་བཤད་ཆོས་མངོན་རྒྱ་མཚོའི་སྙིང་པོ།
  languages:
  - bo
  author: ཀརྨ་པ ༠༩་པ་དབང་ཕྱུག་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9972736700852032
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG5481:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5481
      total_pages: 394
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5481.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9972736700852032
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
